[package]
name = "poirot_core"
version = "0.1.0"
edition = "2024"

[dependencies]
# macro to generate builders through derive
poirot_macro= {version="0.1.0",path="../poirot_macro"}

colorimetry = {version= "0.0.8"}
cozo = {version="0.7.6", features=["compact","minimal","storage-rocksdb","graph-algo","requests","io-uring"]}
# Logging
log  = {version="0.4.28"}
env_logger = {version="0.11"}

rayon = "=1.10"  # otherwise graph-builder don't work, there is a bug in 1.11
thiserror= {version="2.0.17"}

tokio = { version = "1.36", features = ["full"] }
reqwest = {version = "0.12.24", default-features= false,  features = ["json","rustls-tls"]  }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# to parse atom XML
quick-xml = { version = "0.36", features = ["serialize"] }

fancy-regex = "0.16.2" 
async-trait = "0.1.78"

# for the rate limiter, I could switch to chrono
time = {version="0.3.44",features=["serde"]}
governor= {version="0.10.2"}
nonzero_ext= {version="0.3.0"}



rand = {version="0.9.2"}

# provide a macro for declaring lazily evaluated statics in Rust
# used to initialize categories since some are collections of subgroups
lazy_static= "1.4.0"

# used to create AuthorGraph
petgraph= {version="0.8.3"}
uuid= {version="1.19.0",features=["v7"]}