name: Cliff GitHub Action

on:
  push:
    branches: ["main", "features"]
  pull_request:
    branches: ["main"]

jobs:
  git-cliff-action:
    runs-on: ubuntu-latest
    name: Generate changelog with git-cliff
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate a changelog
        id: git-cliff
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --verbose --strip footer --exclude-path ".github/**" --tag 0.0.0
        env:
          OUTPUT: CHANGELOG.md

      - name: Print the changelog
        run: cat "${{ steps.git-cliff.outputs.changelog }}"

      - name: Print the version
        run: echo "${{ steps.git-cliff.outputs.version }}"